### ISSUE TITLE
Unable to use Sandbox environment

### ISSUE THREAD

**Issue by ppmtscory** [paypal/paypal-here-sdk#4]
When I try to connect to the Sandbox, I get an exception that crashes the App.  Below is the log snippet as well as the full log file attached.

```
2017-02-06 14:23:57.5194|DEBUG(9)|cal|Set group Id to 1486412637517
2017-02-06 14:23:57.6024|DEBUG(9)|root|Beginning SDK initialization.
2017-02-06 14:23:57.6864|DEBUG(9)|root|SDK initialization complete.
2017-02-06 14:23:57.7174|INFO(9)|sdk|Setting RetailSDK executing environment to: V-OMA-00874445A.MicrosoftWindowsNT6.2.9200.0.net45.PayPalRetailSDK.Desktop
2017-02-06 14:23:58.6414|DEBUG(9)|cachedServerFile|Remote file load did not return new file. statusCode: 304, undefined
2017-02-06 14:23:58.6524|INFO(9)|features|Version of local feature map: 1.0 remote/cached: 1.1
2017-02-06 14:23:58.6684|DEBUG(9)|features|Replacing local feature map with remote
2017-02-06 14:24:15.3612|DEBUG(9)|sdk|Received composite token {"accessToken":"A103.OoirTyDREX2yfk0IFCQB6IstUOSljxgwWGclnayOOuIv0OW-tkHGpt6JxjWsUMm7.zO80oGdG6iGDeISldyyqZyqmryC","refreshUrl":null,"refreshToken":null,"appId":null,"appSecret":null,"environment":"sandbox"}
2017-02-06 14:24:15.3761|DEBUG(9)|merchant|Loading merchant user info...
2017-02-06 14:24:15.3761|DEBUG(9)|merchant|Loading merchant status...
2017-02-06 14:24:15.8385|DEBUG(9)|paypalrest|GET https://api.sandbox.paypal.com/retail/merchant/v1/status (457ms): undefined
2017-02-06 14:24:15.8553|ERROR(9)|paypalrest|Authenticated request error: An error occurred while sending the request.
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Manticore.NativeServices.<sendRequest>d__4.MoveNext() in C:\Users\aravidas\Documents\GitHub\develop-retail-sdk\platform\win\manticore-win\Manticore.Desktop\NativeServices.cs:line 115
2017-02-06 14:24:15.8793|ERROR(9)|merchant|Merchant initialize failed: code: '-1001' message: 'An error occurred while sending the request.' stack: '   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Manticore.NativeServices.<sendRequest>d__4.MoveNext() in C:\Users\aravidas\Documents\GitHub\develop-retail-sdk\platform\win\manticore-win\Manticore.Desktop\NativeServices.cs:line 115'
2017-02-06 14:24:15.9283|DEBUG(9)|paypalrest|GET https://api.sandbox.paypal.com/v1/identity/openidconnect/userinfo?schema=openid (548ms): undefined
2017-02-06 14:24:16.0663|ERROR(9)|paypalrest|Authenticated request error: An error occurred while sending the request.
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Manticore.NativeServices.<sendRequest>d__4.MoveNext() in C:\Users\aravidas\Documents\GitHub\develop-retail-sdk\platform\win\manticore-win\Manticore.Desktop\NativeServices.cs:line 115
```
[PayPalRetailSDK.zip](https://github.com/paypal/paypal-here-sdk/files/756035/PayPalRetailSDK.zip)

**Comment by and-then** [comment]
This may be a bit outdated but for future reference.

I had a similar issue when initializing the merchant where no api calls returned a value. I managed to fix by setting the security protocol manually

try adding, it requires .net 4.5.2
`System.Net.ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12`

There does seem to be a workaround for earlier versions but i have not tested
`System.Net.ServicePointManager.SecurityProtocol = (SecurityProtocolType)3072`
